// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgHTCSHjAGyQeG82ZrP0ZeuK08pbhwjm0',
    appId: '1:379983705416:web:889998765514ebb433ef7d',
    messagingSenderId: '379983705416',
    projectId: 'honkai-star-retail-cf352',
    authDomain: 'honkai-star-retail-cf352.firebaseapp.com',
    storageBucket: 'honkai-star-retail-cf352.firebasestorage.app',
    measurementId: 'G-47VDB83LCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVhGmJIYlTCcDqCRkv8Bz3Aivd4Q4owAI',
    appId: '1:379983705416:android:29ad267d91f5a2aa33ef7d',
    messagingSenderId: '379983705416',
    projectId: 'honkai-star-retail-cf352',
    storageBucket: 'honkai-star-retail-cf352.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIXW2ha1oh68wZjEDBLcOUq6sOjFcX-I8',
    appId: '1:379983705416:ios:7f57e179949dee3b33ef7d',
    messagingSenderId: '379983705416',
    projectId: 'honkai-star-retail-cf352',
    storageBucket: 'honkai-star-retail-cf352.firebasestorage.app',
    iosBundleId: 'com.example.honkaiStarRetailApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIXW2ha1oh68wZjEDBLcOUq6sOjFcX-I8',
    appId: '1:379983705416:ios:7f57e179949dee3b33ef7d',
    messagingSenderId: '379983705416',
    projectId: 'honkai-star-retail-cf352',
    storageBucket: 'honkai-star-retail-cf352.firebasestorage.app',
    iosBundleId: 'com.example.honkaiStarRetailApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgHTCSHjAGyQeG82ZrP0ZeuK08pbhwjm0',
    appId: '1:379983705416:web:cbbb1a0bf29a4cb933ef7d',
    messagingSenderId: '379983705416',
    projectId: 'honkai-star-retail-cf352',
    authDomain: 'honkai-star-retail-cf352.firebaseapp.com',
    storageBucket: 'honkai-star-retail-cf352.firebasestorage.app',
    measurementId: 'G-XJ4WHFRTV4',
  );
}
